# default: &default
#   adapter: postgresql
#   encoding: unicode
#   user: root
#   password: postgres
#   pool: 5

# development:
#   <<: *default
#   database: oop

# test:
#   <<: *default
#   database: oop_test

# production:
#   <<: *default
#   database: oop



default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: thanhdat97

development:
  <<: *default
  database: oop

test:
  <<: *default
  database: oop_test

production:
  <<: *default
  database: oop
